default_stages:
  - commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: check-toml
      - id: debug-statements

  - repo: local
    hooks:

    - entry: black
      exclude: ^$
      files: ""
      id: black
      language: system
      name: black
      pass_filenames: true
      stages:
        - commit
      types:
        - python
        - file
      types_or: []

    - entry: isort --verbose
      exclude: ^$
      files: ""
      id: isort
      language: python
      name: isort
      pass_filenames: true
      stages:
        - commit
      types:
        - python
      types_or: []

    - entry: ruff
      exclude: ^$
      files: ""
      id: ruff
      language: python
      name: ruff
      pass_filenames: true
      stages:
        - commit
      types:
        - python
      types_or: []

    - entry: mypy
      exclude: ^$
      files: ""
      id: mypy
      language: python
      name: mypy
      pass_filenames: true
      stages:
        - commit
      types:
        - python
      types_or: []
