default_stages:
  - pre-commit

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: check-added-large-files
      - id: trailing-whitespace
      - id: check-toml
      - id: debug-statements

  - repo: local
    hooks:

    - entry: black
      exclude: ^$
      files: ""
      id: black
      language: system
      name: black
      pass_filenames: true
      stages:
        - pre-commit
      types:
        - python
        - file
      types_or: []

    - entry: isort --verbose
      exclude: ^$
      files: ""
      id: isort
      language: python
      name: isort
      pass_filenames: true
      stages:
        - pre-commit
      types:
        - python
      types_or: []

    - id: ruff
      exclude: ^$
      files: ""
      name: ruff
      language: python
      entry: ruff check --force-exclude
      pass_filenames: true
      require_serial: true
      args: []
      stages:
        - pre-commit
      types_or: [python, pyi, jupyter]

    - id: ruff-format
      exclude: ^$
      files: ""
      name: ruff-format
      description: "Run 'ruff format' for extremely fast Python formatting"
      language: python
      entry: ruff format --force-exclude
      pass_filenames: true
      require_serial: true
      args: []
      stages:
        - pre-commit
      types_or: [python, pyi, jupyter]

    - entry: mypy
      exclude: ^$
      files: ""
      id: mypy
      language: python
      name: mypy
      pass_filenames: true
      stages:
        - pre-commit
      types:
        - python
      types_or: []
